### 1. Create a 3x3x3 array with random values

In [36]:
import numpy as np

#a = np.array([[[1,2,3],[4,5,6],[7,8,9]],  [[5,6,2],[1,5,7],[5,3,7]],  [[0,8,9],[9,0,3],[2,1,7]]])

a = np.random.random((3,3,3))
print(a)

[[[0.99821388 0.5730311  0.29246411]
  [0.11569337 0.26159717 0.24194798]
  [0.91050559 0.83564603 0.03013295]]

 [[0.98838132 0.64469263 0.23646205]
  [0.89204767 0.02362363 0.33265127]
  [0.37876237 0.85183492 0.21594148]]

 [[0.69625164 0.78498852 0.22384522]
  [0.88991835 0.25531371 0.36811902]
  [0.47690376 0.20340493 0.54991716]]]


### 2. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal


In [21]:
import random
b = np.zeros((5,5))
k=1
for i in range(5):
    for j in range(5):
        if i==j+1:
            b[i][j] = k
            k = k+1
            
            #b[i][j] = random.randrange(1,5)
            #it will random values between 1 and 4

print(b)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


### 3. Create a 8x8 matrix and fill it with a checkerboard pattern


In [34]:
c = np.zeros((8,8))
for i in range(8):
    for j in range(8):
        if (i+j)%2 == 1:
            c[i][j] = 1

print(c)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


### 4. Normalize a 5x5 random matrix


In [38]:
d = np.random.random((5,5))
print(d)

[[0.72810456 0.17150773 0.85983679 0.9948414  0.41201465]
 [0.73048232 0.99397978 0.96632219 0.53289552 0.35202193]
 [0.9666128  0.97155002 0.39748659 0.12185294 0.82781409]
 [0.17786533 0.81499914 0.84593948 0.12295077 0.11264428]
 [0.390092   0.12872024 0.24322836 0.31912384 0.78887606]]


### 5. How to find common values between two arrays?


In [39]:
a1 = np.array([1,55,67,4,2])
a2 = np.array([2,55,5,6,7])
common = np.intersect1d(a1,a2)
print(common)

[ 2 55]


### 6. How to get the dates of yesterday, today and tomorrow?

In [48]:
yesterday = np.datetime64('today') - 1
print('yesterday was:', yesterday)

today = np.datetime64('today')
print('today is:', today)

tomorrow = np.datetime64('today') + 1
print('tomorrow will be:', tomorrow)

yesterday was: 2023-09-20
today is: 2023-09-21
tomorrow will be: 2023-09-22


### 7. Consider two random array A and B, check if they are equal

In [56]:
x1 = np.array([1,4,3,4])
x2 = np.array([1,2,3,4])
x3 = np.array([1,2,3,4])
t_f1 = np.array_equal(x1,x2)
print(t_f1)
t_f2 = np.array_equal(x3,x2)
print(t_f2)

False
True


### 8. Create random vector of size 10 and replace the maximum value by 0

In [64]:
mat = np.random.random(10)
print(mat)
k = mat.argmax()
print(k)

mat[k] = 0
print(mat)

[0.33177276 0.15749732 0.8305681  0.2505152  0.88197782 0.34789383
 0.47027404 0.32126151 0.33848383 0.98887558]
9
[0.33177276 0.15749732 0.8305681  0.2505152  0.88197782 0.34789383
 0.47027404 0.32126151 0.33848383 0.        ]


### 9. How to print all the values of an array?

In [131]:
aa = np.array([[[1,2],[4,5]], [[12,10],[14,15]]])
print(aa)
print('dimension:',np.ndim(aa))
print('shape:', np.shape(aa))

print()
#n = a5.shape
naa = aa.reshape(1,8)
print(naa)
print()

naaa = naa.reshape(-1)
print(naaa)
for i in naaa:
    print(i)

[[[ 1  2]
  [ 4  5]]

 [[12 10]
  [14 15]]]
dimension: 3
shape: (2, 2, 2)

[[ 1  2  4  5 12 10 14 15]]

[ 1  2  4  5 12 10 14 15]
1
2
4
5
12
10
14
15


### 10. Subtract the mean of each row of a matrix

In [176]:
x = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print("original matrix is:")
print(x)

for i in range(len(x)):
    m = x[i].mean()
    print('mean for row',i+1,':', x[i].mean())
    for j in range(len(x[i])):
        x[i][j] = x[i][j] - m
print(x)

original matrix is:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
mean for row 1 : 2.0
mean for row 2 : 5.0
mean for row 3 : 8.0
mean for row 4 : 11.0
[[-1  0  1]
 [-1  0  1]
 [-1  0  1]
 [-1  0  1]]


### 11. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?

In [184]:
import numpy as np
vector = np.array([3,9,13,54,5])
indices = np.array([2,1,1,4]) #at these indices(index) in vector array, element value will increase by 1
for i in range(len(vector)):
    if i in indices:
        vector[i] = vector[i] + 1
print(vector)

[ 3 10 14 54  6]


### 12. How to get the diagonal of a dot product?


In [102]:
x1 = np.array([[1,2,3],[4,5,6],[1,1,1]])
print("first matrix:\n",x1)
x2 = np.array([[7,8,9],[10,11,12],[1,1,1]])
print("second matrix:\n",x2)
a = np.dot(x1, x2)
print("dot product is:\n",a)
for i in range(len(a)):
    for j in range(len(a)):
        if i==j:
            print(a[i][j])

first matrix:
 [[1 2 3]
 [4 5 6]
 [1 1 1]]
second matrix:
 [[ 7  8  9]
 [10 11 12]
 [ 1  1  1]]
dot product is:
 [[ 30  33  36]
 [ 84  93 102]
 [ 18  20  22]]
30
93
22


### 13. How to find the most frequent value in an array?

In [126]:
x = np.random.randint(0,10,20)
print(x)
#bincount is used to get count of occurence for each element
#method1
freq_no = np.bincount(x).argmax()

#method2
count = np.bincount(x)
freq_no1 = np.argmax(count)

print(freq_no, freq_no1)

[3 1 5 2 0 8 3 9 6 8 1 5 3 8 0 5 4 7 3 4]
3 3


### 14. How to get the n largest values of an array

In [157]:
x = np.array([[1,24,33],[34,5,62],[57,78,59],[105,141,127]])
print(x)
print()

x1 = x.reshape(-1)
print(x1)
print(x1.dtype)

x1.sort()
print("sorted array:", x1)


n = 5
for i in range(len(x1)-1,(len(x1)-n),-1):
    print(x1[i])

[[  1  24  33]
 [ 34   5  62]
 [ 57  78  59]
 [105 141 127]]

[  1  24  33  34   5  62  57  78  59 105 141 127]
int32
sorted array: [  1   5  24  33  34  57  59  62  78 105 127 141]
141
127
105
78


### 15. How to create a record array from a regular array?

In [197]:
import numpy as np

array1 = np.array([
    ("Kaushal", 29, 70),
    ("Krishna", 20, 72),
    ("Kumar", 30, 74)
])

print(array1)
print()
print("Record array:")
result = np.core.records.fromarrays(array1.T, names='col1, col2, col3', formats='S80, f8, i8')
print(result)

[['Kaushal' '29' '70']
 ['Krishna' '20' '72']
 ['Kumar' '30' '74']]

Record array:
[(b'Kaushal', 29., 70) (b'Krishna', 20., 72) (b'Kumar', 30., 74)]


### 16. How to swap two rows of an array?

In [162]:
x = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
x[[0,1]] = x[[1,0]]

print(x)

[[ 4  5  6]
 [ 1  2  3]
 [ 7  8  9]
 [10 11 12]]


### 17. Write python code to reshape to the next dimension of numpy array?

In [166]:
x = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(x.reshape(6,2))

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
